# Generated by Django 3.0 on 2020-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetable',
            old_name='reciepe_vegetables',
            new_name='rec_vegetables',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='rec_veg_latest_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='rec_veg_wt',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
